[package]
name = "fforager-storage"
version = "0.1.0"
workspace = "../../../build"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
fforager-contracts = { version = "0.1.0", path = "../fforager-contracts" }
redb.workspace = true

[lints]
workspace = true
